mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: blog
    username: root
    password: ""
    path: 127.0.0.1
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
logger:
    level: info
    perfix: blog
    director: log
    show_line: true
    log-in-consol: true
system:
    host: 0.0.0.0
    port: 8080
    env: debug
site-info:
    title: SuperMoose's Blog
    version: 0.0.4
    email: kongzhh1101@gmail.com
qq:
    app-id: SuperMoose
    key: a
    redirect: ""
jwt:
    secret: secret
    expire: 999
    issuer: blog
email:
    host: ""
    port: 2222
    user: SuperMoose
    password: ""
    default-from-email: ""
    user-ssl: true
    user-tls: false
qiniu:
    enabeld: false
    access_key: "1"
    secret_key: ""
    bucket: ""
    cdn: ""
    zone: ""
    size: 1.1
upload:
    size: 2
    path: uploads/file
